import type { Metadata } from "next";
import { Inter } from 'next/font/google'
import "./index.css";
import "./scss/style.scss";
import Header from "@/app/components/header/Header";

const getInter = Inter({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-inter',
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Clean Case",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en">
      <head>
        <link href="https://fonts.cdnfonts.com/css/satoshi" rel="stylesheet"></link>
      </head>
      <body className={`antialiased bg-[#171925] text-white/50 overflow-x-hidden ${getInter.variable}`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
